### ISSUE TITLE
Progress Data

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#10]
The current system is a black box - when you send in the request you get no information back on what progress is being made.

# What Data?

The following data should be surfaced by the system:

- Total number of files ServiceX has to run
- Number of files ServiceX has run.
- How many of the files have been copied locally

# Approach

The `tdqm` module seems to be the standard thing used for progress bars in python. The goal is thus twofold:

- Integration points that will give enough information to use tdqm
- An implementation that runs by default that will use tdqm for feedback.

# Features

The following features

- Call back that will update with the following information: total files, files servicex has finished, files servicex is working on. Total files will be None if servicex hasn't started to send useful stats back yet. but the query has started. Note that files processed could be non-zero at that point.
- If an error occurs, then the call-back will be called with a keyword argument, "error" that will point to an exception. This will happen only if servicex has been called - if the error happens before servicex is contacted, no call will be made to the callback.
- Integration that will use `tqdm` that will work in a notebook and will work from the command line.

**Comment by gordonwatts** [comment]
@kyungeonchoi - could you look at the above data and suggest other things that are needed, especially if they are needed to make your current display work.

**Comment by gordonwatts** [comment]
Ping @kyungeonchoi ? This is the last big thing to work on for this release, and I've got most of the rest of the stuff done.

**Comment by kyungeonchoi** [comment]
@gordonwatts , sorry for the slow response! 
Here are two functions that I use to monitor the requests.
- [`async def monitor_requests()`](https://github.com/kyungeonchoi/ServiceXforTRExFitter/blob/06e5ce914962263920ab286a39140af24f844b1a/ServiceXRequests.py#L136)
- [`def monitor_multiple_requests()`](https://github.com/kyungeonchoi/ServiceXforTRExFitter/blob/06e5ce914962263920ab286a39140af24f844b1a/ServiceXRequests.py#L174)
The first function should be straightforward and the second function uses `asyncio` to monitor multiple jobs.

**Comment by gordonwatts** [comment]
Ok, @kyungeonchoi , I think I know what I'm doing now, I'm going to start coding this up. Want to make sure it works for me in a Jupyter notebook as well.
