### ISSUE TITLE
More sensible values for max_workers

### ISSUE THREAD

**Issue by AndrewEckart** [ssl-hep/ServiceX_frontend#131]
@ivukotic was testing out some transformation requests against his local deployment and noticed that 20 transformers were spawned for a dataset with only 17 files. It looks like this is because we set `max_workers=20` by default in `servicexabc.py`.

Two separate areas of concern here:
- Does it ever make sense to spawn more workers than files?
- Can users request arbitrarily many transformers? What happens if I make a request with `max_workers=1000`? Isn't this something the backend should decide based on available resources? (Forgive my ignorance if this is how things work already).

**Comment by gordonwatts** [comment]
Yes - but this isn't a policy that is set in the front end. Logically:

- This should be the max the user wants to use
- The ServiceX backend should limit things to be some max value set by policy (in a yaml file?)
- Really - we need auto scaling - so only what is needed is started. The front-end doesn't know how many files have to be processed until they are done.

So fixing this isn't something that gets sorted out in this software, unfortunately.

Close if you agree! Or feel free to point out things I've missed!

**Comment by AndrewEckart** [comment]
Yes, I understand things now a little bit more than when I opened this issue (though still not perfectly).

My perspective is that:
- The user should not even need to know what a transformer is, let alone how many of them to ask for.
- Furthermore, this isn't really something the user needs control over even if they do know. In 99.9% of cases, the user just wants the data ASAP. The details of how to achieve that should be completely abstracted by the backend. It follows that `max_workers` shouldn't really exist on the frontend or be part of a transformation request.
- It might be a good idea for the backend to limit the amount of resources dedicated to any individual user. A simple way is to add a config value for a max # of transformers as you mention. A more advanced technique would be to implement some kind of fair queueing / scheduling algorithm.
- I think nailing down autoscaling is one of Ben's near-term goals, so we can revisit this in the appropriate repos soon.

**Comment by gordonwatts** [comment]
I agree with everything you wrote with one small caveat - leaving it possible for advanced users - or users running from an analysis facility, the ability to cap the number of workers (as long as it is below the number in the ServiceX yaml file). This is just because there are times a user or analysis facility might have more context and might be able to make a smarter decision.

That said - we don't have a specific use case, so it might not make sense to have this feature until we have an actual use case!

**Comment by AndrewEckart** [comment]
Oh yes, I forgot to mention the most important thing:

We have a student at UChicago who is trying to replicate Marc's scalability studies from earlier in the year. One of these aims is to measure performance on a dataset parameterized by the number of transformers.This is a concrete example of the use cases you mentioned, so we do need to keep a back door for users to specify the maximum number of transformers to use for their request.

**Comment by ivukotic** [comment]
Hi,

I have tested autoscaling and it did not work with the default values. Once I updated values it autoscales fine.
It is a really easy fix and I think the default value should be updated and autoscaling being set on by default.
People should not have a way to even suggest number of transformers.

Cheers,
Ilija

**Comment by gordonwatts** [comment]
@ivukotic - as @AndrewEckart and I have said, allowing the user to specify an upper limit, and the system taking the smaller of that limit and the internally calculated/configured number would be nice to retain. For example, for reasons that @AndrewEckart mentioned. Currently, the number is burried.

**Comment by ivukotic** [comment]
Hi,

There could be two internally calculated limits:

  1.  number of files in the dataset
  2.  a fairsharing one.
But the system should always start from 1 and autoscale up/down. So I don’t see how could user possibly want to lower the upper limit if he/she already does not know how much he/she will get anyhow?

Cheers,
Ilija
