### ISSUE TITLE
Incompatible with Coffea

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX_frontend#152]
Trying to install `coffea` version 0.7.1 alongside serviceX results in the following pip error:\
```
ERROR: servicex 2.1.3 has requirement uproot~=3.7, but you'll have uproot 4.0.6 which is incompatible.
```

**Comment by gordonwatts** [comment]
This is continued fall out from coffea - I moved everything to uproot4 once, but then had to go back because coffea wasn't ready. Looks like it is time to roll forward. FWIW, I don't think there are many things to change - just how datasets are combined.

**Comment by gordonwatts** [comment]
`coffea` has moved to using `awkward` and `uproot` for version 1 and version 4 - we've been using `awkward1` and `uproot4`. That is the source of compatibility. Looks like it might be time to switch back from this transition period.

I hope jim never does anythig like this again. :-)
