### ISSUE TITLE
Support file-list option to dataset request

### ISSUE THREAD

**Issue by ponyisi** [ssl-hep/ServiceX_frontend#160]
When I create a ServiceXDataset I would like to be able to provide the "file-list" instead of "did" option in the REST API. This would allow users to access files from sources outside of Rucio.

**Comment by gordonwatts** [comment]
We might want to move this bug over to the ServiceX repo - as this might require some backend modifications, depending on what files you want to be able to access.

**Comment by gordonwatts** [comment]
Ok - given it is over there, I'm going to close this.
