### ISSUE TITLE
Share ServiceX UUID's between machines

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#172]
As a user, I'd like to run my long-running transform request from one machine, and then move to another and just have the data come down automatically (and not re-run the transform).

It would also be nice, as a user working in a group of analyzers, if someone sent me a file with the query and UUID associations, I could place that someone on my computer and my servicex queries would automatically pick up those datasets.

## Approach

* One of the front-end cache files is a simple UUID <-> md5 query hash.
* If one stores the files someplace that is shared across machines then any servicex instance running will pick up that query -> UUID association
* In the config file make a folder where these can be stored
* Each local machine should write out a uniquely labeled file (so there are no sync issues if you are running on two machines at once)
* Allow a user to create one of these attached to a repository they distribute as well
* All this must be integrated with the way we handle queries that the end point no longer knows about (the `remove_query` implementation). This is tricky because it is now possible to have multiple cache lines for a single query!

**Comment by gordonwatts** [comment]
See https://github.com/iris-hep/opendata-higgs-discovery/issues/35 for original reference to this.

**Comment by gordonwatts** [comment]
The above commit contains an actual description of how we will try to make this work.

**Comment by BenGalewsky** [comment]
What about a URL that represents the transform? The serviceX instance and the uuid of the request -

**Comment by gordonwatts** [comment]
You are right, @BenGalewsky, in the sense that if the person doesn't have the proper info in their `servicex.yaml` file, it will make their lives easier. The only reason I didn't just "do this" was that this means the same type of information was going to be coming from two places and now the behavior would be magic. For example:

- The "name" of the services backend comes from when they first create the `ServiceXDataset`
- But if that query comes from a cache, then the "name" is ignored that is in the code (behind the user's back)
- If the user makes a modification to the query, then the cache will be ignored, and everything will fail b.c. the info isn't in the users `servicex.yaml` file. So one line works fine, but the next line doesn't - makes me worry too much is going on behind the user's back and they won't be able to sort out what is happening.
- What if the `servicex.yaml` file and the cache file specify different endpoint locations? Who wins?
- If the server requires authentication then this does need to fail until the user gets a proper `servicex.yaml` file from the service (I'm imagining some of these files are checked in to github).

I suppose this is an issue of priorities. For a public, open `servicex` end points, should anyone be able to just download and run?? If so, then we can bury the above complex logic, and warning messages when the `servicex.yaml` files does not contain the proper information... Perhaps give the cache precedence over the user's `servicex.yaml` file.

Maybe the fact this complex logic would exist means that the current design is bad and needs a change! :-)

At anyrate, the above was too hard, so I didn't design it in. I am quite open to ideas, however, so, please!

**Comment by gordonwatts** [comment]
Let's leave off the machine version of the cache for now - this analysis version is already enough complexity. And I would likely be the only user of the machine version. For now, I can just copy that directory that contains everything from one place to another.
