### ISSUE TITLE
Misleading error message with missing `servicex.yaml` 

### ISSUE THREAD

**Issue by alexander-held** [ssl-hep/ServiceX_frontend#210]
In the absence of a `servicex.yaml` file defining endpoints, I see the following error message:

> ServiceXException: (ServiceXException(...), 'Unable to find name/type uproot in api_endpoints in servicex.yaml configuration file. Saw only names (default) and types (xaod)')

This sounds as if a `servicex.yaml` file was found, but that my desired endpoint was not included in there. Instead, it would be useful if the error message mentioned that no file was found.

**Comment by ponyisi** [comment]
Fixed in 3.0 client
