### ISSUE TITLE
Submit Transform Requests with Python Function Selects

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX_frontend#216]
_As an analyzer I want to submit transform requests that contain a python function as the select so I can  access transformer features not available through func_adl_

This is directly needed for the PONDD project to enable yt powered transformers. It should also be of interest to uproot users who want to directly write uproot code and bypass func_adl

## Assumptions
1. Users can pass a function into the various `get_data` functions
2. The code for the function will be encoded with base64

**Comment by ponyisi** [comment]
Is this essentially handled by the Python codegen?
