### ISSUE TITLE
Can we make this interface for submitting python code general?

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#222]
All the methods on ServiceX should allow for this, not just a special one. See [this commit](https://github.com/ssl-hep/ServiceX_frontend/commit/5a519b32bfba3bf6f76aec1a708f2a2651e81255) from @BenGalewsky .

**Comment by ponyisi** [comment]
Could you elaborate?

**Comment by ponyisi** [comment]
I believe this is solved by the Python codegen, but reopen if not.
