### ISSUE TITLE
UX for multiple code generators in a single ServiceX end-point

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#252]
As an end-user of a ServiceX datastream, I'd like to be able to specify which code generator is used to generate the code that will power my requested transform. This will allow me to use powerful new transform tools to change the data from an experiment's binary format.

## Assumptions

1. ServiceX needs only a string to tell it what the code generator should be
2. The string is embedded in the JSON that is part of the initial transform request API call (see [post callback](https://github.com/ssl-hep/ServiceX/blob/237f985fa16613b5501acdc92834a42a470f2938/servicex_app/servicex/resources/transformation/submit.py#L93)).
3. The string is simple and user-friendly. Like "atlas-xaod-r21" or "cms-miniaod" or similar.
4. The service can report the list of supported code generators
5. Code generators should be named like docker hub images (atlas/xaod:22)

## Discussion

* Places where this could be specified, and its UX implications.
   * In the `servicex.yaml` file
      * This means your endpoint name will always be associated with a particular code generator. 
      * You would use different endpoint names for different generators in your code, tho they would all end up going to the same web address.
      * This also implies that once you create a dataset in your code, where you specify the end point, you'll always use the same code generator for that data set.
   * As an argument to the creation of the [`ServiceXDataset`](https://github.com/ssl-hep/ServiceX_frontend/blob/master/servicex/servicex.py#L170).
      * The `image` argument already exists here, which gives you the tag your transformer will run.
      * Tigly ties the code generator to the data, not the end-point, which makes sense from a design POV.
   * As an argument to the [`get_data_xxx`](https://github.com/ssl-hep/ServiceX_frontend/blob/master/servicex/servicex.py#L333) method that renders the request to ServiceX.
      * Ties the code-generator specification tightly to the `qastle` (or whatever) query.

The code generator is mainly tied to the dataset, so it seems to make sense to specify it when you specify the dataset. However, this also means that you have to specify a bunch more info when you create the dataset - so the dataset creation is now getting more complex. However, most users will only be using a single code generator, so that will add noise to the code.

At some level, most users will see this interface through something up one level - in another library, like `func_adl_servicex` (or `func_adl`) or similar. So some of the above is about making the capabilities available in an easy-to-use way in those libraries.

## How will other libraries use this?

Here is a current example query for a `xAOD` transform:

```python
   ds =  SXDSAtlasxAODR21("rucio://mc16_13TeV:mc16_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.deriv.DAOD_PHYS.e3601_e5984_s3126_s3136_r10724_r10726_p4164", backend="xaod_r21")
    jets = (ds
            .SelectMany(lambda e: e.Jets())
            .Where(lambda j: (j.pt() / 1000) > 30)
            .Select(lambda j: j.pt() / 1000.0)
            .AsAwkwardArray('JetPt')
            .value())
```

A few things of note:

* The `xaod_r21` already implies a backend web address *and* a generator.

First, if the user has only a single end point in their `servicex.yaml` file:

```python
   ds =  SXDSAtlasxAODR21("rucio://mc16_13TeV:mc16_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.deriv.DAOD_PHYS.e3601_e5984_s3126_s3136_r10724_r10726_p4164", codegen="xaod_r21")
    jets = (ds
            .SelectMany(lambda e: e.Jets())
            .Where(lambda j: (j.pt() / 1000) > 30)
            .Select(lambda j: j.pt() / 1000.0)
            .AsAwkwardArray('JetPt')
            .value())
```

And the `backend` could still be a valid argument incase they had multiple places they were running services queries (this would be mostly a developer or tester feature).

From the point of `falling into a pit of success` it might be nice if this just worked:

```python
   ds =  SXDSAtlasxAODR21("rucio://mc16_13TeV:mc16_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.deriv.DAOD_PHYS.e3601_e5984_s3126_s3136_r10724_r10726_p4164")
    jets = (ds
            .SelectMany(lambda e: e.Jets())
            .Where(lambda j: (j.pt() / 1000) > 30)
            .Select(lambda j: j.pt() / 1000.0)
            .AsAwkwardArray('JetPt')
            .value())
```

And similarly for the `SXDatasetUproot` assuming a `servicex.yaml` file followed some naming conventions (which are currently implemented).

Regardless, this feels more natural than specifying the code generator as an argument to the `value`.

## Proposal

In order of precedence:

1. Allow a `codegen` argument to dataset creation
2. Allow a default code generator to be specified in the `servicex.yaml` file.

## Things that need to be tracked

* Make sure the code generator is part of the local cache hash algorithm so the same dataset with different code generators causes a different cache key!

## Concerns

Some of these will have to be understood before we code this up, others are longer-term.

* How do we properly support reproducibility. For example, if a code generator is updated and produces different results, how do we go back to reproduce what we had before (e.g. compare)?
* Is the current `image` argument to [`ServiceXDataset`](https://github.com/ssl-hep/ServiceX_frontend/blob/master/servicex/servicex.py#L170) too useful to ignore? Can it be replaced by `func_adl` predicates? DOes it make sense if we also specify the code generator (accidentally use the uproot code generator and the xaod transformer. Good times).

**Comment by ponyisi** [comment]
Hi Gordon, Tal,

A couple of things that come to mind (some discussed at the last ServiceX meeting) -
- specifying a code generator amounts to specifying a codegen/transformer stack if it's going to make sense (though for testing reasons it would be good to still be able to specify the transformer image independently).
- this would seem to imply some kind of codegen-transformer pairing registry
- it would be nice to avoid the proliferation of classes like `SXDSAtlasxAODR21` throughout the frontend codebase - it ties the frontend code unnecessarily to the evolution of the transformers (like, why should we need a new frontend release if ATLAS bumps its release numbers?). I'd hope that flexible codegen choice + hosting multiple transformers in a single instance allows for a single, uniform entrypoint for the user.

**Comment by BenGalewsky** [comment]
> * specifying a code generator amounts to specifying a codegen/transformer stack if it's going to make sense (though for testing reasons it would be good to still be able to specify the transformer image independently).

@ponyisi - the deployed code generators know about their preferred transformer image, so users don't _have_ to specify an image. However, as always there is a property in the transform request where a user can provide a specific image they want to use. If the transformer doesn't match the code generator it will fail in many wonderful ways.

**Comment by gordonwatts** [comment]
> * it would be nice to avoid the proliferation of classes like `SXDSAtlasxAODR21` throughout the frontend codebase - it ties the frontend code unnecessarily to the evolution of the transformers (like, why should we need a new frontend release if ATLAS bumps its release numbers?). I'd hope that flexible codegen choice + hosting multiple transformers in a single instance allows for a single, uniform entrypoint for the user.

@ponyisi - I don't know how to avoid this - you need to send down some type information to ServiceX code translator. And you'll want it locally anyway to try to detect mistakes where you make them.

BTW, you can avoid this if you want - it is just you'll get a lot less error checking before the request is sent down to ServiceX. Also, you would lose, on xAOD, the ability to do corrections and systematic errors.

Under the hood, this is just the dataset created with some typing information, as it turns out. So this is a very thin wrapper.

Maybe there is a way around this, but lets get this working and then go from there. But it was the first solution to the issue of not updating the backend everytime ATLAS modified the xAOD release.

**Comment by talvandaalen** [comment]
Hi all,

I've just published an alpha release here: https://github.com/ssl-hep/ServiceX_frontend/releases/tag/2.6.2a1, meant to be used to test the new backend against. This release just adds an optional `codegen` argument to the ServiceXDataset constructor which is added to the json query under the `"codegen"` key.
The plan is to make this more elegant and include logic to read from the default config and user-defined `servicex.yaml` file, but for now this can be used to test the backend just fine.

**Comment by gordonwatts** [comment]
Thanks! This is done, then! :-)
