### ISSUE TITLE
3.0 Update to Documentation

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#279]
* Remove/update old documentation (e.g. servicex read the docs)
* Add appropriate new documentation
* Clean up repo issues referring to old code

**Comment by ketan96-m** [comment]
- [ ] Remove/update old documentation
- [ ] Encourage people to document the code
- [ ] Enlist examples or code snippets that work
- [ ] Embed code from these examples into the CI for deployment on documentation #322

**Comment by ketan96-m** [comment]
Following document shows the people contributing to specific areas of the ServiceX Client.
https://go.illinois.edu/ServicexDocumentationTracker

**Comment by kyungeonchoi** [comment]
@ketan96-m - what is the branch to update documentation? I don't see `documentation` branch in the repo..

**Comment by ponyisi** [comment]
Hi @kyungeonchoi - the branch was merged into 3.0_develop, you can branch from there :-)

**Comment by kyungeonchoi** [comment]
Resolved by #444
