### ISSUE TITLE
Client-side Caching

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#280]
* Caching code needs testing coverage
* Code must be robust against crashes and network loss mid-transform
* Robust against switching between download files and signed url

**Comment by kyungeonchoi** [comment]
### Github issues on caching

- https://github.com/iris-hep/idap-200gbps-atlas/issues/135
- https://github.com/ssl-hep/ServiceX_frontend/issues/375
- https://github.com/ssl-hep/ServiceX_frontend/issues/383
- https://github.com/ssl-hep/ServiceX_frontend/issues/418
- https://github.com/ssl-hep/ServiceX_frontend/issues/213
- https://github.com/ssl-hep/ServiceX_frontend/issues/280 (This one)
- https://github.com/ssl-hep/ServiceX_frontend/issues/396
- https://github.com/ssl-hep/ServiceX_frontend/issues/361

### Working branches

- https://github.com/ssl-hep/ServiceX_frontend/pull/318
   - Solve #361 

### Wish list for 3.0

- Code must be robust against crashes and network loss mid-transform (Gordon)
- Robust against switching between download files and signed url (Gordon)
- Caching code needs testing coverage (Gordon)
- Download to non-temporary space (KyungEon)

**Comment by gordonwatts** [comment]
After 3.0.1 triage, turned @kyungeonchoi 's list into:

### Github issues on caching

**Bug**
- https://github.com/ssl-hep/ServiceX_frontend/issues/375
- https://github.com/ssl-hep/ServiceX_frontend/issues/418
- https://github.com/ssl-hep/ServiceX_frontend/issues/213
- https://github.com/ssl-hep/ServiceX_frontend/issues/396
- https://github.com/ssl-hep/ServiceX_frontend/issues/361
- https://github.com/ssl-hep/ServiceX_frontend/issues/285
- https://github.com/ssl-hep/ServiceX_frontend/issues/295

**In progress updates to pacakge**
- https://github.com/ssl-hep/ServiceX_frontend/issues/468
- https://github.com/ssl-hep/ServiceX_frontend/issues/280 (This one)

So this can be closed as soon as the last issue (#468) is closed.

**Comment by ponyisi** [comment]
All the 3.0.1 fixes are in, so closing.
