### ISSUE TITLE
Stage downloads from minio

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#294]
Download to a temporary file from minio and only rename once 100% complete download. Otherwise we can give users partial files

**Comment by prajwalkkumar** [comment]
https://min.io/docs/minio/linux/developers/python/API.html#fget-object-bucket-name-object-name-file-path-request-headers-none-ssec-none-version-id-none-extra-query-params-none-tmp-file-path-none 

Minio already uses a tmp file location to download files to , and then performs a rename. I think this should take care of this issue @gordonwatts ?

**Comment by gordonwatts** [comment]
Oh! That is great! In that case this is done!
