### ISSUE TITLE
No network access required for fully cached query

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#295]
User should not need to connect to the internet when accessing a fully cached/downloaded query.

* Example: when you create the dataset, it queries for the code-gen backends

**Comment by kyungeonchoi** [comment]
We need a test for this

**Comment by BenGalewsky** [comment]
This should be the case. Let's verify and see if we can close this

**Comment by ponyisi** [comment]
Added a test, verified code passes (#439 )
