### ISSUE TITLE
On windows the cache is set to /tmp - which causes bad things when you do `cache clear`

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#304]
On windows, not tested on `linux`, if you do not set the cache path, it defaults to `/tmp`.

This is great and everything works until you do `servicex cache clear`, where it tries to delete every file in your `/tmp` directory. On Windows, some of those files fail, so it stops pretty quickly. But I would imagine on `Linux` that it might actually get quite a bit done...

We should be using a sub-directory of `/tmp` - like `/tmp/servicex-<username>` or similar. There is code inside the original `servicex` library that does this. This allows it to run on a shared machine and still use the `/tmp` directory.

**Comment by BenGalewsky** [comment]
Closed via #343
