### ISSUE TITLE
TCut Datset

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX_frontend#308]
_As an analyze I want to perform basic cuts using the TCut language so I can use familiar tools_

# Description
Bring in @kyungeonchoi implementation of TCut to Qastle translator into ServiceX client. 

Users will call a new factory method on the ServiceX client to obtain a TCutDataset. This will accept a string with the TCut query

**Comment by ponyisi** [comment]
The uproot-raw queries basically cover the use cases for TCut, so I propose that we indefinitely postpone this one.
