### ISSUE TITLE
Better messages when backend is wrong

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#335]
As a user, I'd like to know right away when I mess up the backend specification (or leave it off).

```
ServiceXException: (ServiceXException(...), 'Failed to get request errors for 5b9f74d0-c97a-4b49-b8f0-e1f2af7d77c8: 404 - <!doctype html>\n<html lang=en>\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n')
```

People don't know what a "URL" is - as they have mostly never entered it. Further, I think the default is currently `localhost`, and perhaps we should change that too.

* Better default
* Error message that more specifically directs people.
*

**Comment by ponyisi** [comment]
Is this still an issue?

**Comment by ponyisi** [comment]
I feel this is a 2.0 client issue, so I will close. Reopen if not.
