### ISSUE TITLE
Find alternative to deprecated nest-asyncio dependency

### ISSUE THREAD

**Issue by matthewfeickert** [ssl-hep/ServiceX_frontend#355]
On 2024-03-06 https://github.com/erdewit/nest_asyncio was archived, meaning that [`nest-asyncio`](https://pypi.org/project/nest-asyncio/) is now unsupported and should be treated as deprecated (for very sad reasons I'm afraid, as [the project author died](https://github.com/erdewit/ib_insync/commit/ef5ea29e44e0c40bbadbc16c2281b3ac58aa4a40)).

The dependency is used in

https://github.com/ssl-hep/ServiceX_frontend/blob/4b8403cec933ef0b22f70e21d57c84d3d069f4e7/servicex/databinder/databinder_deliver.py#L33-L39

and was added in PR #333. @kyungeonchoi it looks like this was targeting a pretty particular issue of nested event loops in async workflows, so while I don't think it is a high priority to migrate _now_ having the `servicex` client depend on archived and unsupported software is a problem that will need to get mitigated in the future. Do you have any thoughts on alternative libraries?

**Comment by kyungeonchoi** [comment]
Thanks @matthewfeickert for following this up! Most of databinder features are now migrated to the core library of `servicex==3.X` and all files under `databinder` directory are deprecated. I still want to review my old codes under `databinder` directory before I delete them. I think it's okay to close this issue.

**Comment by gordonwatts** [comment]
Ops - sorry - I don't understand what action was taken. In 3.0 is the nest-asyncio dependency removed? If so, then I agree, this should be closed. Otherwise either a issue to remove it should be created or this should remain open until there is a plan.

**Comment by kyungeonchoi** [comment]
@BenGalewsky can correct me - but my understanding is we simply use `asyncio.gather` now
