### ISSUE TITLE
Change naming convention on 3.0 client library

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX_frontend#362]
### Goal
Straightforward and intuitive names for newcomers (especially w/o backend knowledge). 

### Names for discussion

1. `Codegen`
   - We might want to choose what we want to expose to normal users between `codegen` and `transformer`. It can be quite confusing since we often mention different types of transformers
1. Codegen name `uproot`
   - There are `python`, `uproot-raw` and `uproot` for uproot transformer. `uproot` codegen should be something like `uproot-funcadl`. And maybe `uproot-python` for consistency
1. `SignedURLs`
   - More self-explanatory name?
1. `root-file` as `OutputFormat`
   - `-file` only exists for root format
   - It might be good to change to `root-tree` as we will add `root-rntuple`(?) in the future
1. else?

**Comment by BenGalewsky** [comment]
We've agreed that we won't make back-end changes for these, so the unfortunate `root-file` value will have to be translated in the client

**Comment by kyungeonchoi** [comment]
1-2. Stays same
3. URLs
4. `parquet`, `root-ttree` and `root-rntuple`
