### ISSUE TITLE
Website cancel is missed by the 3.0 front end code

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#370]
As a user I'd like to submit a transform from my request, go to the web, click the cancel button. And when that happens, I expect the script to crash with a "canceled" error or similar.

## Repro

1. Submit a SX query of any kind using this library (the 3.0 version).
2. Go to the web site and load up your dashboard
3. Click the `cancel` button

Expected Action: The script that is waiting on the run should crash very quickly.

What currently happens: the script continues to run forever.

**Comment by ponyisi** [comment]
@ketan96-m  something you can look at?

**Comment by ponyisi** [comment]
Do we know if the fact of the cancellation is correctly added to the returned TransformStatus object?
