### ISSUE TITLE
Temporary(?) solution for MinIO object store access

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX_frontend#395]
## Problem
- The current approach (list objects in a bucket) to download files or urls from object-store is broken for a bucket more than 1k files ([ref - S3 API Limits](https://min.io/docs/minio/container/operations/checklists/thresholds.html))
- Need a reliable (temporary? but immediate) solution before we have an ultimate solution which requires refactoring of backend and frontend

## Approach
- Explore possible avenues within the same protocol (HTTPS) to have a temporary solution until we have a refactored approach

**Comment by ponyisi** [comment]
One possibility is to switch away from the minio client to something that has a slightly higher level of abstraction: for example, the `boto3` library will handle the pagination in the library.

**Comment by kyungeonchoi** [comment]
@ponyisi - Thanks for your comments!

`boto3` looks cool but it seems like it's a wrapper around `Minio` and uses the same functions. Since our current limitation is coming from the `list_objects()` call, we'd like to explore other options.

I don't know whether partial files (or being written files) in a bucket show up by a `list_objects()` call. We can check this from tests. It might be also useful to check number of files downloaded from MinIO and processed from input dataset (or file list).

**Comment by ponyisi** [comment]
I'm certain boto3 isn't a wrapper around minio (boto3 is the official Amazon library for S3, minio is an independent implementation).

The core point is that there is a very well defined process to list all the files in a bucket, even with minio: you ask for an object list, if you get a thousand objects you ask for the next thousand (using start_after in minio), and keep going until you don't get any more objects. There's no limitation that you can only get 1000 files from a bucket, you just need to make a loop. The value of boto3 is that it would have the code already to do this, so we wouldn't have to write the function ourselves. But, again, there is no fundamental limitation here, just that in writing this code we forgot that this is how minio works.

**Comment by ketan96-m** [comment]
Not all files are uploaded to Minio bucket.
Due to lack of python api for listing al the objects for the minio. I used the CLI `mc` command to manually connect to a bucket when I submitted the transform to check the number of files uploaded. I found that not all files are uploaded to the bucket.

Steps taken:
1. pip install minio
2. https://min.io/docs/minio/linux/reference/minio-mc.html - downloaded the mc tool
3. Ran the bigger_uproot file
```
from servicex import ServiceXSpec, General, Sample
from servicex.func_adl.func_adl_dataset import FuncADLQuery
from servicex.servicex_client import deliver
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("servicex")
logger.setLevel(logging.DEBUG)


def bigger_uproot():
    query = FuncADLQuery().Select(lambda e: {'el_pt': e['el_pt']})

    spec = ServiceXSpec(
        General=General(
            ServiceX="servicex-uc-af",
            Codegen="uproot",
            OutputFormat="parquet",
            Delivery="SignedURLs"
        ),
        Sample=[
            Sample(
                Name="bigger_uproot",
                RucioDID="user.kchoi:user.kchoi.fcnc_tHq_ML.Wjets.v11", #1102 files
                Tree="nominal",
                Query=query
            )
        ]
    )
    print(len(deliver(spec)['bigger_uproot']))


if __name__ == "__main__":
    bigger_uproot()

```
4. `mc alias set ALIAS HOSTNAME ACCESS_KEY SECRET_KEY`
5. Added a breakpoint in the download files and allowed some time to pass to check if all files are uploaded
6. Count of files in bucket `mc find ALIAS/<BUCKET NAME> | find /c /v ""` (on WINDOWS so `find /c /v "" ` for counting lines)
7. Only gave back 1066 files

Need to find out why some files are lost.

**Comment by ketan96-m** [comment]
Switching the package `async_minio` to `minio` used in the minio_adapter.py returns the correct number of files from the bucket. 
The list_object of async_minio returns a list of coroutines whereas the list_object of minio returns a iterator. 
The master branch uses the minio module however, the async_minio was introduced in the 3.0 branch. Was there any reason was introducing this?

**Comment by ponyisi** [comment]
@gordonwatts , @BenGalewsky - not sure what to make of this minio/async_minio difference, any suggestions?

**Comment by gordonwatts** [comment]
We need @BenGalewsky here. the `async` version was introduced because it is async and thus does not block a thread, making the client performance better. I'd be a little surprised if it can't return more than 1000 files - did any one look at the issues? And if it returns a list of co-routines, then one just has to async wait on those?

**Comment by ketan96-m** [comment]
@gordonwatts I looked into this issue. I am not entirely sure how a nested async works.
The list_object method for async_minio was awaited but even then it would only return 1000 files.
Does it improve the client performance if async function is awaited inside another async function?

download_files -> awaits minio_adapter.list_object -> awaits async_minio.list_object -> List[]

vs

download_files -> awaits minio_adapter.list_object -> minio.list_objects -> Iterator

**Comment by ponyisi** [comment]
The `miniopy_async` library does indeed have a bug meaning it doesn't handle paging properly when getting the list of objects. I have filed an issue at https://github.com/hlf20010508/miniopy-async/issues/26 and the corresponding PR is https://github.com/hlf20010508/miniopy-async/pull/27 .

**Comment by ponyisi** [comment]
I think we can close this one, then? Things should work with the latest miniopy_async.
