### ISSUE TITLE
Get this running under 3.8

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#4]
Currently fails one test - but the failure appears to be in the test code, not in the actual code.

Blocker: all the asyncio stuff (see #12) and the way we were throwing exceptions was not compatible with `nest_asyncio` (see #13).

**Comment by gordonwatts** [comment]
It actually works fine in 3.8.0, 3.8.1. In 3.8.2 it fails, and the failure is due to the code/trick i'm using to allow nested running (e.g. so it can run from python and jupyter notebooks). Another case of python not quite getting it right.

See this github bug report: https://github.com/erdewit/nest_asyncio/issues/20

Once that gets fixed, we will have python 3.8.2 (or better) support.

**Comment by erdewit** [comment]
It is fixed in nest_asyncio v1.3.0.
