### ISSUE TITLE
Examples Use the New Dataset Property of Sample

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX_frontend#445]
# Problem 
We introduced a new way of specifying the datasets. The current examples all show the old way.

# Approach
Update the examples to use the `Dataset` property of Sample. See [example](https://github.com/ssl-hep/ServiceX_frontend/blob/2dfb069200bf80572941fe78893684f3b859e7af/tests/test_databinder.py#L143)

**Comment by kyungeonchoi** [comment]
All examples are update to use `Dataset` by #444.
