### ISSUE TITLE
Is unmaintained dependency ccorp-yaml-include-relative-path critical?

### ISSUE THREAD

**Issue by matthewfeickert** [ssl-hep/ServiceX_frontend#448]
The current `3.0_develop` ([`3.0.0-beta-1`](https://github.com/ssl-hep/ServiceX_frontend/releases/tag/3.0.0-beta-1)) has the requirement

https://github.com/ssl-hep/ServiceX_frontend/blob/2dfb069200bf80572941fe78893684f3b859e7af/pyproject.toml#L53

which was added by @ponyisi in PR #386. Looking at the PyPI release history (https://pypi.org/project/ccorp-yaml-include-relative-path/#history), `ccorp-yaml-include-relative-path` was last released in July 2020 and the linked source repository (https://github.com/marsoloGit/ccorp_yaml_include) is a fork of https://github.com/Tristan-Sweeney-CambridgeConsultants/ccorp_yaml_include and was [last updated in June 2020](https://github.com/marsoloGit/ccorp_yaml_include/tree/163789cc516997e033ecc2f488eab2c075c7c66f).

The project seems to not be maintained at all, which raises both security and sustainability concerns. Is this dependency critical and totally unique or could it be replaced?

(This was noticed given Issue https://github.com/ssl-hep/ServiceX_frontend/issues/352).

**Comment by ponyisi** [comment]
We would like to keep it, yes. It adds key functionality that is hard to replicate without us basically reimplementing this package. One would not really expect development on it as long as the underlying API that it works with doesn't break, and I'd prefer to cross that bridge once we get there.

**Comment by matthewfeickert** [comment]
> It adds key functionality that is hard to replicate without us basically reimplementing this package

What does the rest of the world do to achieve this functionality? They are definitely not using `ccorp-yaml-include-relative-path`.

> One would not really expect development on it as long as the underlying API that it works with doesn't break

Yes, though it seems that this is also a security concern to be asking people and facilities to use code that isn't maintained. I think the best thing it has going for it security wise is that no one uses it: https://www.pepy.tech/projects/ccorp-yaml-include-relative-path

**Comment by ponyisi** [comment]
It's a very specific case of trying to implement "include yaml in yaml". As far as I can tell everyone else who tries to do this (which is not so many people in itself) does it by implementing the code themselves, which requires detailed knowledge of the parser engine that I would prefer to avoid having to bring into the ServiceX client.

If someone is able to find another Python YAML engine that supports this feature with an actively developed package, I'll be happy to consider it.
