### ISSUE TITLE
Interest in adding pre-commit?

### ISSUE THREAD

**Issue by matthewfeickert** [ssl-hep/ServiceX_frontend#451]
As it seems that there are a few instances in PRs like PR https://github.com/ssl-hep/ServiceX_frontend/pull/444 where the linting fails, is there interest in adding `pre-commit` hooks (which are optional) and pre-commit.ci (which would run the equivalent of `pre-commit run --all-files` on every commit) so that devs don't have to worry about fixing this stuff manually? https://learn.scientific-python.org/development/guides/style/#pre-commit

**Comment by ponyisi** [comment]
Hi @matthewfeickert , for now we've put in a pre-commit check but not pre-commit.ci (we'll fix issues as they come up as files get edited - it's almost all just whitespace stuff). Thanks for the suggestion.
