### ISSUE TITLE
Docs: Update About Page

### ISSUE THREAD

**Issue by matthewfeickert** [ssl-hep/ServiceX_frontend#465]
In the `3.0_develop` branch the [About Page](https://servicex-frontend.readthedocs.io/en/latest/about.html) in the docs is very outdated. It doesn't tell people who don't already know about the IRIS-HEP Slack how to get help

https://github.com/ssl-hep/ServiceX_frontend/blob/21aea65baf20e40c5e6f29249f64637f3423dee9/docs/about.rst?plain=1#L5-L8

and the demos/tutorials listed

https://github.com/ssl-hep/ServiceX_frontend/blob/21aea65baf20e40c5e6f29249f64637f3423dee9/docs/about.rst?plain=1#L26-L32

are 4 years old and so almost certainly not correct anymore. There are also newer demos.

**Comment by ponyisi** [comment]
Any chance you could take this one, @gordonwatts ?

**Comment by kyungeonchoi** [comment]
Resolved by https://github.com/ssl-hep/ServiceX_frontend/pull/526
