### ISSUE TITLE
Frontend crashes while working transform is in progress are not saved

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#468]
The following sequence:

1. Your code submits a transform.
2. While waiting for it to finish, you have a crash or disconnect
3. Re-run, and a new transform is fired off, even if the old transform is still running and doing just fine.

Expected behavior:

* Same transform should always be used
* Running transform that hasn't failed should be reused.

**Comment by gordonwatts** [comment]
This worked in the 2.0 client, but perhaps this is a non-goal now, @ponyisi ?

The reason it comes up is that sometimes running these really big datasets you can have an hour or more in time, and it is very easy to get a disconnect when that happens.

**Comment by ponyisi** [comment]
It's a goal but I think we should make it a 3.0.1 or 3.0.2 feature? Basically, look in the local cache for a submitted but not completed transform and recover state from that.

**Comment by kyungeonchoi** [comment]
I've updated the list for client caching - https://github.com/ssl-hep/ServiceX_frontend/issues/280#issuecomment-2327264275

**Comment by gordonwatts** [comment]
Feel free to move this to another milestone!
