### ISSUE TITLE
docs: "Getting Started" docs page not on navigation tree and using pre-v3.0.x API

### ISSUE THREAD

**Issue by matthewfeickert** [ssl-hep/ServiceX_frontend#492]
As of 53226cddfa74d5cbd4f2e1940062c172c20e6489, the ["Getting Started" docs page](https://servicex-frontend.readthedocs.io/en/3.0.0/getting_started.html#xaod), which includes an example of transforming a PHYS dataset and applying calibrations is not listed anywhere on the docs navigation tree or on a subtree.

https://github.com/ssl-hep/ServiceX_frontend/blob/53226cddfa74d5cbd4f2e1940062c172c20e6489/docs/index.rst?plain=1#L61-L74

This means that the only way to find it is to either already know that it exists, or to search for it.

The information on this page should get added to the navigation tree or should get moved to a new page that is already on the navigation tree.

**Comment by matthewfeickert** [comment]
Also the examples in [`docs/getting_started.rst`](https://github.com/ssl-hep/ServiceX_frontend/blob/53226cddfa74d5cbd4f2e1940062c172c20e6489/docs/getting_started.rst) aren't using the `v3.0.0` API,

https://github.com/ssl-hep/ServiceX_frontend/blob/53226cddfa74d5cbd4f2e1940062c172c20e6489/docs/getting_started.rst#L22-L31

, so they should get updated.

**Comment by ponyisi** [comment]
Hi @matthewfeickert - I think page is intentionally not visible and is more of a placeholder for something we might put in later. @kyungeonchoi and @gordonwatts can confirm if we want to keep something like this or just delete the thing. But as you note it is not linked to by anything.

**Comment by matthewfeickert** [comment]
> I think page is intentionally not visible and is more of a placeholder for something we might put in later. 
> ...
> But as you note it is not linked to by anything.

Thanks for the info. It would be useful to have some information in the public docs on how to use ServiceX to do transformations with PHYS, so regardless of if it is this page or another, it would be great to see this.

**Comment by kyungeonchoi** [comment]
Hi @matthewfeickert - that page was intentionally hidden and kept for a while as a reference. I believe the latest client documentation includes the [func-adl example for PHYSLITE](https://servicex-frontend.readthedocs.io/en/latest/examples.html#func-adl-xaod-query-example) and a [link to the full func-adl documentation](https://servicex-frontend.readthedocs.io/en/latest/query_types.html#funcadl-query-type). Please feel free to open this ticket again.

**Comment by matthewfeickert** [comment]
@kyungeonchoi My point in https://github.com/ssl-hep/ServiceX_frontend/issues/492#issue-2565142416 is that there isn't anything in the docs that shows how to go about applying calibrations.

**Comment by kyungeonchoi** [comment]
@matthewfeickert - that's in the [func-adl documentation](https://gordonwatts.github.io/xaod_usage/chapters/calibration.html#). IMO, a separate (detailed) documentation for func-adl pro users (who want to do calibration on PHYS with ServiceX) makes more sense.
