### ISSUE TITLE
`servicex dataset delete` CLI command reports "Dataset N not found"

### ISSUE THREAD

**Issue by ponyisi** [ssl-hep/ServiceX_frontend#528]
Running `servicex dataset delete N` seems to always print "Dataset N not found" even though the delete succeeds. I suspect this is because the CLI uses the return value of `ServiceXClient.delete_dataset` to determine what it prints
https://github.com/ssl-hep/ServiceX_frontend/blob/c4c8562687927f5dd27089cd033145875672a33e/servicex/app/datasets.py#L122
and following the call chain, it's the return value of `ServiceXAdapter.delete_dataset`
https://github.com/ssl-hep/ServiceX_frontend/blob/c4c8562687927f5dd27089cd033145875672a33e/servicex/servicex_adapter.py#L174
which never actually has a path that returns anything other than None.

**Comment by BenGalewsky** [comment]
Resolve via #529
