### ISSUE TITLE
Errors from ServiceX that aren't JSON do not tell us much

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#61]
As a user I want to be able to understand what errors are comming back from servicex when the service totally fails:

- The request ID
- If the response isn't in JSON, it would be good to have the HTML dumped instead.

**Comment by AndrewEckart** [comment]
I like the example of the Twilio API [here](https://blog.restcase.com/rest-api-error-codes-101/), i.e. we should use correct HTTP status codes and send back a JSON body containing additional information (I think we already do this in many cases).

The frontend client can then use conditional logic to raise an appropriate `ServiceXException`, passing on the message from the server.

**Comment by gordonwatts** [comment]
That would be fine - one would need to add a story to the servicex app that scans for all "exceptions" and make sure they come back properly.

**Comment by ponyisi** [comment]
Essentially the same complaint as #502 (except we want the request ID too)

**Comment by ponyisi** [comment]
Resolved by #501
