### ISSUE TITLE
Compatibility with Uproot ServiceX 

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX_frontend#64]
As an end-user I'd like to use the same interface to access xAOD and uproot backends (or nearly as the same as possible.

## Current Status

The new system didn't provide a way to push a `tree-name` through for the `uproot` backend. This is what a modern `func_adl` `xAOD` query looks like:

```python
  from func_adl_xAOD import ServiceXDatasetSource
  r = await ServiceXDatasetSource('atlas_xaod_rucio_did') \
        .SelectMany('lambda e: e.Jets("AntiKt4EMTopoJets")') \
        .Select('lambda j: j.pt()/1000.0') \
        .AsPandasDF('JetPt') \
        .value_async()
```

And that generates some `qastle` for the query that looks like the following currently:

```
(call ResultTTree (call Select (call SelectMany (call EventDataset 'ServiceXDatasetSource') (lambda (list e) (call (attr e 'Jets') 'AntiKt4EMTopoJets'))) (lambda (list j) (/ (call (attr j 'pt')) 1000.0))) 'JetPt' 'treeme' 'file.root')
```

## Proposal

- `ServiceX` can have a number of back-ends.
- The API for talking to the service, which is exposed through the `ServiceCDataset` object should not change as a function of the backend.
- The `selection` argument is only interpreted by the code generator portion of the service.
   - But it must be of a form that travels in a JSON WebAPI query - but other than that, there are no service imposed restrictions.
- The tree name should thus be encoded in the `qastle`.

The above code, to run against the `uproot` backend might look like the following, then:

```python
  from func_adl_xAOD import ServiceXDatasetSource
  r = await ServiceXDatasetSource('atlas_xaod_rucio_flat_root_files_did', tree_name='CollectionTree') \
        .SelectMany('lambda e: e.antikt4_jets') \
        .Select('lambda j: j/1000.0') \
        .AsPandasDF('JetPt') \
        .value_async()
```

And that generates some `qastle` for the query that looks like the following currently:

```
(call ResultTTree (call Select (call SelectMany (call EventDataset 'ServiceXDatasetSource', 'CollectionTree') (lambda (list e) (attr e 'antiktr_jets'))) (lambda (list j) (/ j 1000.0))) 'JetPt' 'treeme' 'file.root')
```

**Comment by gordonwatts** [comment]
The original text of this from @kyungeonchoi 👍 

> Current ServiceX Frontend doesn't work with Uproot ServiceX due to the missing field `tree-name` in the frontend query. In principle, a qastle query can take care of this, but it requires updates on `ServiceX_Code_Generator_FuncADL_uproot`, `ServiceX_xAOD_CPP_transformer`, and `func_adl.uproot`. 
> 
> In the meantime, I would like to have a valid `servicex` python package with an optional argument of `tree-name` for Uproot transformer.

**Comment by gordonwatts** [comment]
Written like this, there are no modifications needed in this frontend code, I think!

**Comment by gordonwatts** [comment]
And this now works!
