### ISSUE TITLE
Fix up error message to be more clear

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#99]
`ServiceX instance does not know about cached query 20e8a136-1eb5-4767-8e8b-0d1fb62afa37. Please resubmit.` - make it clear that the cache was cleared so this should now work

**Comment by AndrewEckart** [comment]
Just to play devil's advocate, why throw an error at all? Why not just make a new request automatically without additional user input?

**Comment by gordonwatts** [comment]
Excellent point. That is the right thing to do. When I first did this I thought "oh - that would be painful, lets wait for a later time to code that up". But when I look at this, I should evaluate again how hard it would be, given the redesign has now happened.
